# .github/workflows/create_release_asset.yml

name: Create Release Asset from Telegram File

on:
  repository_dispatch:
    types: [upload_file_to_release]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 步骤 1: 检出代码，这样才能访问到 download_script.py
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2 (可选): 调试，打印收到的数据
      - name: 'Debug: Print client payload'
        run: echo "${{ toJSON(github.event.client_payload) }}"

      # 步骤 3: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # 步骤 4: 安装 Python 依赖
      - name: Install dependencies
        run: python -m pip install requests

      # 步骤 5: 运行独立的 Python 脚本来下载文件
      - name: Download file from Telegram
        id: download
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FILE_ID: ${{ github.event.client_payload.file_id }}
          FILE_NAME: ${{ github.event.client_payload.file_name }}
        run: python download_script.py # <--- 关键修改在这里

      # 步骤 6: 获取当前日期 (YYYY-MM-DD)
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # 步骤 7: 创建或更新 Release，并上传文件
      - name: Create or Update Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.download.outputs.downloaded_file_name }}
          tag_name: "daily-backup-${{ steps.date.outputs.today }}"
          name: "Daily Backup - ${{ steps.date.outputs.today }}"
          body: |
            Files automatically uploaded from Telegram on ${{ steps.date.outputs.today }}.
            This release is automatically managed.