# /.github/workflows/create_release_asset.yml

name: 通过 cURL 和 GitHub API 直接上传 Release Asset

on:
  repository_dispatch:
    types: [upload_file_to_release]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. 检出代码
        uses: actions/checkout@v4

      - name: 2. 设置 Python 环境和依赖
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install requests

      - name: 3. 从 Telegram 下载文件
        id: download
        timeout-minutes: 60
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FILE_ID: ${{ github.event.client_payload.file_id }}
          ORIGINAL_FILE_NAME_B64: ${{ github.event.client_payload.original_file_name_b64 }}
        run: python download_script.py

      - name: 4. 准备 Release 信息
        id: release_info
        run: |
          RELEASE_TAG="daily-backup-$(TZ='Asia/Shanghai' date +'%Y-%m-%d')"
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: 5. 创建 Release 并获取上传 URL
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.release_tag }}
          release_name: "每日备份 - ${{ steps.release_info.outputs.release_tag }}"
          body: "通过机器人自动备份的文件。"
          draft: false
          prerelease: false

      - name: 6. 使用 cURL 上传文件 (最终方案)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 从上一步获取关键信息
          UPLOAD_URL="${{ steps.create_release.outputs.upload_url }}"
          FILE_PATH="${{ steps.download.outputs.file_path }}"
          ORIGINAL_NAME="${{ steps.download.outputs.original_name }}"
          
          # 对原始文件名进行 URL 编码，这是 API 的要求
          URL_ENCODED_NAME=$(jq -sRr @uri <<< "$ORIGINAL_NAME")
          
          echo "准备上传文件: $FILE_PATH"
          echo "在 Release 中将显示为: $ORIGINAL_NAME"
          echo "最终上传 URL: $UPLOAD_URL?name=$URL_ENCODED_NAME"
          
          # 直接调用 cURL 与 GitHub API 对话
          curl \
            --request POST \
            --url "$UPLOAD_URL?name=$URL_ENCODED_NAME" \
            --header "Authorization: token $GITHUB_TOKEN" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@$FILE_PATH"