# /.github/workflows/create_release_asset.yml

name: 通过官方 Action 上传 Release Asset

on:
  repository_dispatch:
    types: [upload_file_to_release]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须，用于创建/获取 Release

    steps:
      - name: 1. 检出代码
        uses: actions/checkout@v4

      - name: 2. 设置 Python 环境和依赖
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install requests

      - name: 3. 从 Telegram 下载文件
        id: download
        timeout-minutes: 60
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FILE_ID: ${{ github.event.client_payload.file_id }}
          ORIGINAL_FILE_NAME_B64: ${{ github.event.client_payload.original_file_name_b64 }}
        run: python download_script.py

      - name: 4. 准备 Release 信息
        id: release_info
        run: |
          RELEASE_TAG="daily-backup-$(TZ='Asia/Shanghai' date +'%Y-%m-%d')"
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: 5. 创建或找到 Release 并获取上传 URL
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.release_tag }}
          release_name: "每日备份 - ${{ steps.release_info.outputs.release_tag }}"
          body: "通过机器人自动备份的文件。"
          draft: false
          prerelease: false
        continue-on-error: true # 关键！如果已存在，则继续

      - name: 6. 获取已存在的 Release 的上传 URL
        if: steps.create_release.outcome == 'failure'
        id: get_existing_release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = releases.data.find(r => r.tag_name === '${{ steps.release_info.outputs.release_tag }}');
            if (release) {
              core.setOutput('upload_url', release.upload_url);
            }
        
      # --- 核心修改：使用 GitHub 官方的上传 Action ---
      - name: 7. 上传文件到 Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 根据之前步骤的结果，决定使用哪个 upload_url
          upload_url: ${{ steps.create_release.outputs.upload_url || steps.get_existing_release.outputs.upload_url }}
          
          # 要上传的文件的本地路径
          asset_path: ${{ steps.download.outputs.file_path }}
          
          # 在 Release 中显示的文件名
          asset_name: ${{ steps.download.outputs.original_name }}
          
          # 内容类型，通常可以自动检测
          asset_content_type: application/octet-stream